G_stages/urls.py
from os import path
from . import views
from . import views 
from django.urls import path  
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import creer_groupe, autocomplete_etudiants
urlpatterns = [
    path('', views.login, name='login'),
    path('index', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
   


   # dep
    path('dep/<int:pk>/update/', views.depUpdateView.as_view(), name='dep_update'),
    path('dep/<int:pk>/delete/', views.depDeleteView.as_view(), name='delete_dep'),
    path('dep/', views.dep, name='dep'),
    path('create_dep/', views.depCreateView.as_view(), name='create_dep'),


    # entre
    path('entre/<int:pk>/update/', views.entreUpdateView.as_view(), name='entre_update'),
    path('entre/<int:pk>/delete/', views.entreDeleteView.as_view(), name='delete_entre'),
    path('entre/', views.entre, name='entre'),
    path('create_entre/', views.entreCreateView.as_view(), name='create_entre'),

    
    path('et/', views.et, name='et'),
    path('add_etudiant/', views.add_etudiant, name='add_etudiant'),
    # etud
    path('etud/<int:pk>/update/', views.etudUpdateView.as_view(), name='etud_update'),
    path('etud/<int:pk>/delete/', views.etudDeleteView.as_view(), name='delete_etud'),
    path('etud/', views.etud, name='etud'),
    path('createetud/', views.etudCreateView.as_view(), name='create_etud'),

     path('encours/', views.encours, name='encours'),



    
   # Type_Encadrant
    path('Type_Encadrant/<int:pk>/update/', views.Type_EncadrantUpdateView.as_view(), name='Type_Encadrant_update'),
    path('Type_Encadrant/<int:pk>/delete/', views.Type_EncadrantDeleteView.as_view(), name='delete_Type_Encadrant'),
    path('type_Encadrant/', views.type_Encadrant, name='type_Encadrant'),
    path('create_Type_Encadrant/', views.Type_EncadrantCreateView.as_view(), name='create_Type_Encadrant'),


    
   # Type_stage
    path('type_stage/<int:pk>/update/', views.type_stageUpdateView.as_view(), name='type_stage_update'),
    path('type_stage/<int:pk>/delete/', views.type_stageDeleteView.as_view(), name='delete_type_stage'),
    path('type_stage/', views.type_stage, name='type_stage'),
    path('create_type_stage/', views.type_stageCreateView.as_view(), name='create_type_stage'),

     #Simester
    path('simester/<int:pk>/update/', views.simesterUpdateView.as_view(), name='simester_update'),
    path('simester/<int:pk>/delete/', views.simesterDeleteView.as_view(), name='delete_simester'),
    path('simester/', views.simester, name='simester'),
    path('create_simester/', views.simesterCreateView.as_view(), name='create_simester'),


    # encadrant
    path('encadrant/<int:pk>/update/', views.encadrantUpdateView.as_view(), name='encadrant_update'),
    path('encadrant/<int:pk>/delete/', views.encadrantDeleteView.as_view(), name='delete_encadrant'),
    path('encadrant/', views.encadrant, name='encadrant'),
    path('createencadrant/', views.encadrantCreateView.as_view(), name='create_encadrant'),

    #etd
    path('etd/', views.etd, name='etd'),
    path('addetd/', views.addetd, name='addetd'),
    #encad
    path('encad/', views.encad, name='encad'),
     #stg
    path('stg/', views.stg, name='stg'),
     #stg
    path('stage/', views.stage, name='stage'),
    path('ajouter_groupe/',views.ajouter_groupe, name='ajouter_groupe'),
    path('ajouter_stage/',views.ajouter_stage, name='ajouter_stage'),
    path('ajouter_encd/',views.ajouter_encd, name='ajouter_encd'),

    
   
    path('import/', views.import_excel, name='import_excel'),
    

    path('creer-groupe/', creer_groupe, name='creer_groupe'),
    path('autocomplete-etudiants/', autocomplete_etudiants, name='autocomplete_etudiants'),

    path('export_excel/', views.export_excel, name='export_excel'),
    
    path('export_excel/', views.export_excel, name='export_excel'),
    

    
    path('compte/', views.compte, name='compte'),
    
]

PI_S4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('G_stages.urls')),
]

G_stages/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def _str_(self):
        return "User: "+self.username


class Dep(models.Model):
    
    libele = models.CharField(max_length=40,null=False)
     
    def _str_(self):
        return self.id
    
    
class Entre (models.Model):
    
    libele = models.CharField(max_length=40,null=False)
     
    def _str_(self):
        return self.id

 
    

class Etud (models.Model):
    matricule = models.IntegerField(max_length=40,null=False ) 
    Nom = models.CharField(max_length=40,null=False)
    prenom = models.CharField(max_length=40,null=False)
    Dep=models.ForeignKey(Dep, on_delete=models.CASCADE)
    
    
    
    def _str_(self):
        return self.id 
       
 
    
 
    
class Type_Encadrant(models.Model):
    type = models.CharField(max_length=40,null=False)
    
    def _str_(self):
        return self.id
    


     
    

class Simester(models.Model):
    libele = models.CharField(max_length=40,null=False)
    
    def _str_(self):
        return self.id
   

class Type_stage(models.Model):
    libele = models.CharField(max_length=40,null=False)
    
    def _str_(self):
        return self.id
    


class Encadrent(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    email = models.EmailField()
    numero = models.CharField(max_length=20)
    

    def _str_(self):
        return self.id
    




    




class grp(models.Model):
    idSimester = models.ForeignKey(Simester, on_delete=models.CASCADE )
    idEtud = models.ForeignKey(Etud, on_delete=models.CASCADE )

    class Meta:
        unique_together = ('idSimester', 'idEtud')

    libele = models.CharField(max_length=50)
    # membres = models.ManyToManyField('Etud')
    membres = models.CharField(max_length=50)

    def _str_(self):
        return self.id

class Stage(models.Model):
    titre = models.CharField(max_length=50)
    dattedebut = models.DateField(max_length=50)
    dattefin= models.DateField(max_length=50)
    datesoutenance = models.DateField(max_length=50)
    lieu = models.CharField(max_length=50)
    Annee = models.CharField(max_length=50)
    status = models.BooleanField(default=True)
    grp=models.ForeignKey(grp, on_delete=models.CASCADE, to_field='id' )
    def _str_(self):
        return self.id
    



class Encdprof(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    email = models.EmailField()
    numero= models.CharField(max_length=20)
    

    def _str_(self):
        return self.id
class Encadrer (models.Model):
    Stage=models.ForeignKey(Stage, on_delete=models.CASCADE)
    Encadrent=models.ForeignKey(Encadrent, on_delete=models.CASCADE)

    def _str_(self):
        return self.id


class contenir (models.Model):
    grp=models.ForeignKey(grp, on_delete=models.CASCADE, to_field='id' )
    Dep=models.ForeignKey(Dep, on_delete=models.CASCADE)

G_stages/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password, check_password 
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.shortcuts import render
from django.views.generic import UpdateView, DeleteView, CreateView
import pandas as pd

from django.shortcuts import render
# Create your views here.
from django.conf import settings
def index(request):
    if request.session.get('username', None):
        x = request.session['username']
        return render(request, 'index.html', {"name": x})
    else:
        return redirect('login')


 


def login(request):
    if request.session.get('username', None):
        return redirect('index')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        if not len(username):
            messages.warning(request, "username is empty")
            redirect('login')
        elif not len(password):
            messages.warning(request, "password is empty")
            redirect('login')
        else:
            pass
        if User.objects.filter(username=username):
            user = User.objects.filter(username=username)[0]
            password_hash = user.password
            resp = check_password(password, password_hash)
            if resp == 1:
                request.session['id'] = user.id
                request.session['username'] = username
                return redirect('index')
            else:
                messages.warning(request, "username or password is incorrect")
                redirect('login')
        else:
            messages.warning(request, "account 404")
            redirect('login')
    return render(request, 'login.html', {})


# Logs
def logout(request):
    for key in list(request.session.keys()):
        del request.session[key]
    return redirect('login')

def register(request):
    if request.session.get('username', None):
        return redirect('index')
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        if User.objects.filter(username=username) or User.objects.filter(email=email):
            messages.warning(request, "account already exist")
        else:
            password = request.POST['password']
            error = []
            if (len(username) < 3):
                error.append(1)
                messages.warning(
                    request, "Username Field must be greater than 3 character.")
            if (len(password) < 5):
                error.append(1)
                messages.warning(
                    request, "Password Field must be greater than 5 character.")
            if (len(email) == 0):
                error.append(1)
                messages.warning(request, "Email field can't be empty")
            if (len(error) == 0):
                password_hash = make_password(password)
                user = User(username=username,
                            password=password_hash, email=email)
                user.save()
                messages.info(request, "account created successfully")
                redirect('register')
            else:
                redirect('register')
    return render(request, 'register.html', {})

#dep
def dep(request):
    
    dep = Dep.objects.all()
    return render(request, 'dep.html', {"dep": dep})


class depCreateView(CreateView):
    model = Dep
    template_name = 'dep_form.html'
    fields = '__all__'
    success_url = reverse_lazy('dep')


class depUpdateView(UpdateView):
    model = Dep
    form_class = depForm
    template_name = 'update_dep.html'
    success_url = reverse_lazy('dep')


class depDeleteView(DeleteView):
    model = Dep
    template_name = 'dep_confirm_delete.html'
    success_url = reverse_lazy('dep')



#entreprise
def entre(request):
    
    entre = Entre.objects.all()
    return render(request, 'entre.html', {"entre": entre})


class entreCreateView(CreateView):
    model = Entre
    template_name = 'entre_form.html'
    fields = '__all__'
    success_url = reverse_lazy('entre')


class entreUpdateView(UpdateView):
    model = Entre
    form_class = entreForm
    template_name = 'update_entre.html'
    success_url = reverse_lazy('entre')


class entreDeleteView(DeleteView):
    model = Entre
    template_name = 'entre_confirm_delete.html'
    success_url = reverse_lazy('entre')



#et
def et(request):
    dep=Dep.objects.all()
    etud =Etud.objects.all()
    return render(request,'etud_form.html' ,{"etud": etud,"dep": dep})
#etud
def etud(request):
     
    etud = Etud.objects.all()
    return render(request, 'etud.html', {"etud": etud})



class etudCreateView(CreateView):
    model = Etud
    model = Dep
    template_name = 'etud_form.html'
    fields = '__all__'
    success_url = reverse_lazy('etud')

from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from .models import Etud
from .forms import etudForm
class etudUpdateView(UpdateView):
    model = Etud
    form_class = etudForm
    template_name = 'update_etud.html'

    def get_success_url(self):
        dep = self.object.Dep
        success_url = reverse_lazy('etud') + f'?dep={dep}'
        return success_url


class etudDeleteView(DeleteView):
    model = Etud
    template_name = 'etud_confirm_delete.html'
    success_url = reverse_lazy('etud')    

#encours
def encours(request):
    return render(request, 'encours.html')    





#EN_type
def type_Encadrant(request):
    
    type_Encadrant = Type_Encadrant.objects.all()
    return render(request, 'Type_Encadrant.html', {"type_Encadrant": type_Encadrant})


class Type_EncadrantCreateView(CreateView):
    model = Type_Encadrant
    template_name = 'Type_Encadrant_form.html'
    fields = '__all__'
    success_url = reverse_lazy('type_Encadrant')


class Type_EncadrantUpdateView(UpdateView):
    model = Type_Encadrant
    form_class = Type_EncadrantForm
    template_name = 'update_Type_Encadrant.html'
    success_url = reverse_lazy('type_Encadrant')


class Type_EncadrantDeleteView(DeleteView):
    model = Type_Encadrant
    template_name = 'Type_Encadrant_confirm_delete.html'
    success_url = reverse_lazy('type_Encadrant') 




#Type_stage
def type_stage(request):
    
    type_stage = Type_stage.objects.all()
    return render(request, 'type_stage.html', {"type_stage": type_stage})


class type_stageCreateView(CreateView):
    model = Type_stage
    template_name = 'type_stage_form.html'
    fields = '__all__'
    success_url = reverse_lazy('type_stage')


class type_stageUpdateView(UpdateView):
    model = Type_stage
    form_class = Type_stageForm
    template_name = 'update_type_stage.html'
    success_url = reverse_lazy('type_stage')


class type_stageDeleteView(DeleteView):
    model = Type_stage
    template_name = 'type_stage_confirm_delete.html'
    success_url = reverse_lazy('type_stage') 






#Simester
def simester(request):
    
    simester = Simester.objects.all()
    return render(request, 'simester.html', {"simester": simester})


class simesterCreateView(CreateView):
    model = Simester
    template_name = 'simester_form.html'
    fields = '__all__'
    success_url = reverse_lazy('simester')


class simesterUpdateView(UpdateView):
    model = Simester
    form_class = simesterForm
    template_name = 'update_simester.html'
    success_url = reverse_lazy('simester')


class simesterDeleteView(DeleteView):
    model = Simester
    template_name = 'simester_confirm_delete.html'
    success_url = reverse_lazy('simester') 





#encadrant
def encadrant(request):
    
    encadrant = Encadrent.objects.all()
    return render(request, 'Encadrent.html', {"encadrant": encadrant})


class encadrantCreateView(CreateView):
    model = Encadrent
    template_name = 'Encadrent_form.html'
    fields = '__all__'
    success_url = reverse_lazy('encadrant')


class encadrantUpdateView(UpdateView):
    model = Encadrent
    form_class = encadrantForm
    template_name = 'update_Encadrent.html'
    success_url = reverse_lazy('encadrant')


class encadrantDeleteView(DeleteView):
    model = Encadrent
    template_name = 'Encadrent_confirm_delete.html'
    success_url = reverse_lazy('encadrant')    





#encad
def encad(request):
    return render(request, 'ecd.html')

#stg
def stg(request):
    return render(request, 'stg.html')

 
 

def ajouter_groupe(request):
    if request.method == 'POST':
        Nom = request.POST['Nom']
        prenom = request.POST['prenom']
        email = request.POST['email']
        filiere = request.POST['filiere']
        libele = request.POST['libele']
        groupe = Groupe(Nom=Nom, prenom=prenom, email=email, filiere=filiere, libele=libele)
        groupe.save()
        return render(request, 'encours.html')
    else:
        return render(request, 'etd.html')
    

def ajouter_stage(request):
    if request.method == 'POST':
        titre = request.POST['titre']
        dattedebut = request.POST['dattedebut']
        dattefin = request.POST['dattefin']
        datesoutenance = request.POST['datesoutenance']
        lieu = request.POST['lieu']
        Annee = request.POST['Annee']
        stage = Stage(titre=titre, dattedebut=dattedebut, dattefin=dattefin, datesoutenance=datesoutenance, lieu=lieu, Annee=Annee)
        stage.save()
        return render(request, 'encours.html')
    else:
        return render(request, 'stg.html')



def ajouter_encd(request):
    if request.method == 'POST':
        nom = request.POST['nom']
        prenom = request.POST['prenom']
        email = request.POST['email']
        profile = request.POST['profile']
        
        encd = Encadrent(nom=nom, prenom=prenom, email=email, profile=profile)
        encd.save()
        return render(request, 'encours.html')
    else:
        return render(request, 'ecd.html')
    
#stage

G_stages/templates/Encadrent_form.html
{% extends "base/base.html" %} {% block body %}
<h1>Create a new  encadrant</h1>
<form method="post" class="form-control">
    <div class="form-group">
        {% csrf_token %} {{ form.as_p }}
    </div>
    <input type="submit" value="Create" class="btn btn-success">
</form>
{% endblock %}

G_stages/templates/compte.html
<a class="nav-link" href="/logout">Deconnexion</a>

G_stages/templates/e_entre.html
{% extends "base/base.html" %} {% block body %}
<h1>encadre_entreprise</h1>
<a href="{% url 'create_e_entre' %}" class="btn btn-success" style="width: max-content;">Ajouter</a>

<table class="table">
    <thead>
        <tr>
           
            <th scope="col">nom</th>
            <th scope="col">prenom</th>
            <th scope="col">email</th>
            <th scope="col">numero</th> 
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for e_entre in e_entre %}
        <tr>
             
            <th scope="row">{{e_entre.Nom}}</th>
            <th scope="row">{{e_entre.prenom}}</th>
            <th scope="row">{{e_entre.email}}</th>
            <th scope="row">{{e_entre.numero}}</th>

            <td><a class="btn btn-primary btn-xs" href="{% url 'e_entre_update' e_entre.id  %}"><span class="glyphicon glyphicon-edit">Update</span></a></td>
            <td><a href="{% url 'delete_e_entre' e_entre.id  %}" class="btn btn-danger">Cancel</a></td>

        </tr>
        {%endfor%}
    </tbody>
</table>


{% comment %}
<div class="alert alert-primary" role="alert"> {% endcomment %}
</div>

{% endblock %}

G_stages/templates/e_entre_form.html
{% extends "base/base.html" %} {% block body %}
<h1>Create a new  encadre_entreprise</h1>
<form method="post" class="form-control">
    <div class="form-group">
        {% csrf_token %} {{ form.as_p }}
    </div>
    <input type="submit" value="Create" class="btn btn-success">
</form>
{% endblock %}

G_stages/templates/ecd.html
{% extends "base/base.html" %} {% block body %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://bootswatch.com/4/yeti/bootstrap.min.css">
  <title>Encadrant</title>
</head>
<body>
<pre> <a href="{% url 'stg' %}">stage</a>                               <a href="{% url 'encad' %}">Encadrant</a>                                       <a href="{% url 'etd' %}">Identification sur groupe </a>  </pre>
<pre><a href="{% url 'encad' %}">Encadrant Academy</a>                    <a href="{% url 'encad' %}">Encadrant professionnel</a>  </pre>
<div class="container mt-4">
  <form class="form-group" method="post" action="{% url 'ajouter_encd' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="nom">Nom :</label>
      <input type="text"  class="form-control" id="nom"   placeholder="Nom">
    </div>
    <div class="form-group">
      <label for="nom">Prenom :</label>
      <input type="text"  class="form-control" id="prenom"   placeholder="Prenom">
    </div>
    <div class="form-group">
      <label>E-mail : </label>
      <input type="email" class="form-control"  name="E-mail" placeholder="E-mail" >
    </div>
    <div class="form-group">
      <label>Numero: </label>
      <input type="number" class="form-control"  name="numero" placeholder="Numero" >
    </div class="form-group">
    <label for="profile">Profile : </label>
    <select type="text" id="profile" name="profile" >
      <option>ENSIGNANT</option>
      <option>PROFETIONNEL</option>
    <div>
  <br>
    </div>
    <input type="submit" value="Ajouter" class="btn btn-primary btn-block">
  </form>
</div>
</body>
</html>
      {% endblock %}
      

G_stages/templates/entre.html
{% extends "base/base.html" %} {% block body %}
<h1>entreprise</h1>
<a href="{% url 'create_entre' %}" class="btn btn-success" style="width: max-content;">Ajouter</a>

<table class="table">
    <thead>
        <tr>
           
            <th scope="col">libele</th>
             
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for entre in entre %}
        <tr>
             
            <th scope="row">{{entre.libele}}</th>
             

            <td><a class="btn btn-primary btn-xs" href="{% url 'entre_update' entre.id  %}"><span class="glyphicon glyphicon-edit">Update</span></a></td>
            <td><a href="{% url 'delete_entre' entre.id  %}" class="btn btn-danger">Cancel</a></td>

        </tr>
        {%endfor%}
    </tbody>
</table>


{% comment %}
<div class="alert alert-primary" role="alert"> {% endcomment %}
</div>

{% endblock %}

G_stages/templates/entre_confirm_delete.html
{% extends "base/base.html" %} {% block body %}
<h1>Are you sure you want to delete this entriprise?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger">
    <a href="{% url 'entre' %}" class="btn btn-dark">Cancel</a>
</form>
{% endblock %}

G_stages/templates/etd.html
{% extends "base/base.html" %} {% block body %}
<!DOCTYPE html>
<html>
<head>
    <title>Créer un groupe</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>   
        var selectedEmployees = [];
        $(document).ready(function () {
            $("#matricule").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "{% url 'autocomplete_etudiants' %}",
                        type: "POST",
                        dataType: "json",
                        data: { matricule: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item.Nom,
                                    value: item.matricule
                                };
                            }));
                        }
        
        
                    });
                },
                select: function (event, ui) {
                    $("#matricule").val(ui.item.label); // Set display text
                    $("#matricule1").val(ui.item.value); // Set hidden value
                    var selectedMatricule = ui.item.label;
                    $("#divAddAnother").append("<li>" + ui.item.label + "</li>");
                    $("#matricule").val("");
                    $("#SelectedEmployeeIds").val(function (index, value) {
                        return value + ui.item.value + ",";
                    });
                    return false;
                }
            }).autocomplete("source")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div>" + item.Nom + "</div>")
                    .appendTo(ul);
            };
        });
        function updateSelectedEmployeesList() {
            $("#divAddAnother").empty();
            selectedEmployees.forEach(function (etudiants) {
                $("#divAddAnother").append("<li>" + etudiants.matricule + " - " + etudiants.Nom + "</li>");
            });
        }
        
        $("form").submit(function (event) {
            event.preventDefault();
            var libele = $("#id_libele").val();
            var idSimester = $("#id_idSimester").val();
            var idEtud = $("#id_idEtud").val();
        
            // Créez une chaîne de caractères contenant les matricules des étudiants sélectionnés
            var matricules = selectedEmployees.map(function (etudiants) {
                return etudiants.matricule;
            }).join(',');
        
            // Mettez à jour les champs du formulaire avec les valeurs sélectionnées
            $("#matricule").val(matricules);
        
            // Soumettez le formulaire
            $("form").unbind("submit").submit();
          });
        
            </script>




</head>
<body>
<pre> <a href="{% url 'stg' %}">stage</a>                               <a href="{% url 'encad' %}">Encadrant</a>                                       <a href="{% url 'etd' %}">Identification sur groupe </a>  </pre>


    
    <h1>Créer un groupe</h1>
    <div class="container mt-4">
        <form  class="form-group" method="post">
       
            {% csrf_token %}
            <div class="form-group">
              <label for="id_idSimester">IdSimester :</label>
              <input type="number" class="form-control" name="idSimester" id="id_idSimester">
           </div>
            <div class="form-group">
              <label for="id_idEtud">IdEtud :</label>
              <input type="number" class="form-control"  name="idEtud" id="id_idEtud">
            </div>
            <div class="form-group" >
              <label for="id_libele">Libelé :</label>
              <input type="text" class="form-control" name="libele" id="id_libele">
          </div>
          <div class="form-group">
              <label for="matricule">Membres :</label>
              <input type="text" class="form-control" name="matricule" id="matricule">
              <input type="hidden" class="form-control" name="matricule1" id="matricule1" />
    
          </div>
            <div class="form-group">
                <ul id="divAddAnother">
                </ul>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Enregistrer</button>
        </form>
    </div>

{% endblock %}
     
    
</body>
</html>
<!-- 
<div class="container mt-4">
    <form class="form-group" method="post" action="{% url 'ajouter_encd' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="nom">Nom :</label>
        <input type="text"  class="form-control" id="nom"   placeholder="Nom">
      </div>
      <div class="form-group">
        <label for="nom">Prenom :</label>
        <input type="text"  class="form-control" id="prenom"   placeholder="Prenom">
      </div>
      <div class="form-group">
        <label>E-mail : </label>
        <input type="email" class="form-control"  name="E-mail" placeholder="E-mail" >
      </div>
      <div class="form-group">
        <label>Numero: </label>
        <input type="number" class="form-control"  name="numero" placeholder="Numero" >
      </div class="form-group">
      <label for="profile">Profile : </label>
      <select type="text" id="profile" name="profile" >
        <option>ENSIGNANT</option>
        <option>PROFETIONNEL</option>
      <div>
    <br>
      </div>
      <input type="submit" value="Ajouter" class="btn btn-primary btn-block">
    </form>
  </div> -->

G_stages/templates/etud_confirm_delete.html
{% extends "base/base.html" %} {% block body %}
<h1>Are you sure you want to delete this etudiants?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger">
    <a href="{% url 'etud' %}" class="btn btn-dark">Cancel</a>
</form>
{% endblock %}

G_stages/templates/import_excel.html
<!DOCTYPE html>
<html>
<head>
    <title>Importation d'un fichier Excel</title>
</head>
<body>
    <h1>Importation d'un fichier Excel</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file" accept=".xlsx">
        <input type="submit" value="Importer">
    </form>
</body>
</html>

G_stages/templates/simester_confirm_delete.html
{% extends "base/base.html" %} {% block body %}
<h1>Are you sure you want to delete this semestre?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger">
    <a href="{% url 'simester' %}" class="btn btn-dark">Cancel</a>
</form>
{% endblock %}

G_stages/templates/simester_form.html
{% extends "base/base.html" %} {% block body %}
<h1>Create a new semestre</h1>
<form method="post" class="form-control">
    <div class="form-group">
        {% csrf_token %} 
        <label for="libele">libele :</label>
      <input type="text" id="libele" name="libele" required><br><br>
    </div>
    <input type="submit" value="Create" class="btn btn-success">
</form>
{% endblock %}